## ----------------------------------------------------------------------
## Travis CI build script for Greenplum Database Open Source Project.
## ----------------------------------------------------------------------

language: c

branches:
  only:
  - travis

git:
  submodules: false

addons:
    apt:
        config:
            retries: true
        sources: &common_sources
            - ubuntu-toolchain-r-test
        packages: &common_packages
            - gcc-8
            - libxml2
            - libxml2-dev
            - libevent-dev
            - libperl-dev
            - g++-8
            - python-dev
            - python-yaml
            - libapr1-dev
            - libzstd1
            - libzstd1-dev
            - python-pip
            - net-tools
            - ssh

matrix:
    include:
        # OS and Compiler variations
        # ----------------------------------------------------------------
        #
        # Ubuntu Bionic on aarch64, gcc 8, without compression libraries, unit tests
        - os: linux
          arch: arm64
          dist: bionic
          compiler: gcc
          env:
              - tests=unit T=debug C="--without-zlib --without-libbz2 --without-zstd --without-quicklz"
              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
          addons:
              apt:
                  sources:
                      - *common_sources
                  packages:
                      - *common_packages
        # Ubuntu Bionic on aarch64, gcc 8, without compression libraries, installcheck
        - os: linux
          arch: arm64
          dist: bionic
          compiler: gcc
          env:
              - tests=installcheck T=debug C="--without-zlib --without-libbz2 --without-zstd --without-quicklz"
              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
          addons:
              apt:
                  sources:
                      - *common_sources
                  packages:
                      - *common_packages
        - os: linux
          arch: amd64
          dist: bionic
          compiler: gcc
          env:
              - T=debug C="--without-zlib --without-libbz2 --without-zstd --without-quicklz"
              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
          addons:
              apt:
                  sources:
                      - *common_sources
                  packages:
                      - *common_packages
#        - os: linux
#          arch: amd64
#          dist: bionic
#          compiler: gcc
#          env:
#              - T=debug C="--without-zlib --without-libbz2 --without-zstd --without-quicklz"
#              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
#          addons:
#              apt:
#                  sources: *common_sources
#                  packages: *common_packages

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

python:
    - "2.7"

before_install:
    - eval "${OVERRIDE_CC}"
    - eval "${OVERRIDE_CXX}"
    - |
      if [ "${TRAVIS_COMPILER}" = clang ]; then
        case "${TRAVIS_OS_NAME}" in
          linux)
            sudo ln -sv ../../bin/ccache /usr/lib/ccache/${CC}
            sudo ln -sv ../../bin/ccache /usr/lib/ccache/${CXX}
            ;;
          osx)
            PATH=/usr/local/opt/ccache/libexec:$PATH
            ;;
        esac
      fi
      echo "RemoveIPC=no" | sudo tee -a /etc/systemd/logind.conf
      sudo systemctl daemon-reload
      sudo systemctl restart systemd-logind

## ----------------------------------------------------------------------
## Install supporting Python modules
## ----------------------------------------------------------------------

install:
    - mv /home/travis/.cache/pip /home/travis/temppip
    - python -m pip install --user --upgrade pip
    - python -m pip install --user --pre psutil
    - python -m pip install --user lockfile
    - python -m pip install --user setuptools

## ----------------------------------------------------------------------
## Perform build:
##        Skipping this one : travis_wait 50 make -s unittest-check
## ----------------------------------------------------------------------

before_script:
    - ssh-keygen -t "rsa" -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}

script:
  - |
      set -eo pipefail
      if [ "$T" = "debug" ]; then
        service sshd status
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 `hostname` ". /home/travis/build/amitdkhan-pg/gpdb-build-arm/trial_python/greenplum_path.sh; /bin/hostname"
        cat /etc/os-release
        grep RemoveIPC  /etc/systemd/logind.conf
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --enable-cassert \
            --enable-debug \
            --enable-debug-extensions \
            --with-perl \
            --with-python \
            --disable-orca \
            --with-openssl \
            --with-ldap \
            --with-libcurl \
            --with-libxml \
            --enable-mapreduce \
            --enable-orafce \
            $C
        travis_wait 50 make install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        if [ "$tests" = "unit" ]; then
            make -s unittest-check
        fi
        if [ "$tests" = "installcheck" ]; then
            make -C gpAux/gpdemo cluster
            source gpAux/gpdemo/gpdemo-env.sh
            make -C src/test/regress installcheck-small
        fi
      fi
  - |
      set -eo pipefail
      if [ "$T" = "production" ]; then
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --with-perl \
            --with-python \
            --disable-orca \
            --with-openssl \
            --with-ldap \
            --with-libcurl \
            --with-libxml \
            --enable-mapreduce \
            --enable-orafce \
            $C
        make install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        make -s unittest-check
        make -C gpAux/gpdemo cluster
        source gpAux/gpdemo/gpdemo-env.sh
        make -C src/test/regress installcheck-small
      fi
  - |
      set -eo pipefail
      if [ "$T" = "macos" ]; then
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --with-perl \
            --with-python \
            --disable-orca \
            --enable-orafce \
            --disable-gpfdist \
            --disable-pxf \
            --disable-gpcloud \
            --without-zstd \
            $C
        make -s install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        make -s unittest-check
      fi

after_script:
  - source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
  - postgres --version
  - gpssh --version
